# API Information
VERSION: 0.1.0
APP_NAME: Fastberry
ADMIN_EMAIL: fastberry@example.com

# Installed Apps
INSTALLED_APPS:

# Development Apps
DEVELOPMENT_APPS:

# Querying
QUERYING:
  items_per_page: 50

# Allowed Hosts
ALLOWED_HOSTS:
  # 8080 (Front-End)
  - http://localhost:8080
  - http://127.0.0.1:8080
