# API Information
VERSION: 0.0.1
APP_NAME: Book-Store
ADMIN_EMAIL: deadpool@example.com

# Installed Apps
INSTALLED_APPS:
  - auth

# Development Apps
DEVELOPMENT_APPS:
  - demo
  - examples

# Querying
QUERYING:
  items_per_page: 50

# Allowed Hosts
ALLOWED_HOSTS:
  # 8080
  - http://localhost:8080
  - http://127.0.0.1:8080
  # 8081
  - http://localhost:8081
  - http://127.0.0.1:8081
  # 3000
  - http://localhost:3000
  - http://127.0.0.1:3000

# Permissions
# [strawberry-permissions](https://strawberry.rocks/docs/guides/permissions)
PERMISSIONS:
  # - auth.permissions.IsAuthorized

# MiddleWare
# [starlette-middleware](https://www.starlette.io/middleware/)
MIDDLEWARE:
  # - auth.middleware.AuthenticatedCookieMiddleware

GENERATES: "graphql"
