# API Information
VERSION: 0.1.0
APP_NAME: Fastberry
ADMIN_EMAIL: fastberry@example.com

# GraphQL (Output Folder)
GENERATES: graphql

QUERYING:
  items_per_page: 50
  max_depth: 4

ALLOWED_HOSTS:

INSTALLED_APPS:

DEVELOPMENT_APPS:

MIDDLEWARE:

EXTENSIONS:

PERMISSIONS:
