# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Folder
files: ^src/

# Repos
repos:
  # Pre-Commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # SSort
  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
      - id: ssort

  # Black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  # iSort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # PyLint
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
