site_name: Fastberry
site_url: https://hlop3z.github.io/fastberry
repo_url: https://github.com/hlop3z/fastberry
copyright: Copyright © Hlop3z

nav:
  - Fastberry:
      - Introduction: index.md
      - Settings: settings.md
      - Environments:
          - Variables: environments/variables.md
      - Applications:
          - Introduction: applications.md
          - CRUD: crud.md
          - Commands: commands.md
          - Router: routers.md
      - Middleware, Extension and Permissions:
          - Workflow: middleware/workflow.md
          - Middleware: middleware/middleware.md
          - Extension: middleware/extension.md
          - Permission: middleware/permissions.md
          - Plugin: middleware/plugin.md
      - Application Programming Interface:
          - Fastberry API: apis/fastberry.md
          - GraphQL API: apis/graphql.md

  - Getting Started:
      - Installation:
          - PyPi with Pipenv: getting-started/installation.md
          - Template: getting-started/template.md
      - Apps:
          - Demo-App: getting-started/demoapp.md
          - First-App: getting-started/firstapp.md

theme:
  name: material
  locale: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.annotate
    # - navigation.expand
  icon:
    logo: material/bike-fast

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
