site_name: Fastberry
site_url: https://hlop3z.github.io/fastberry
repo_url: https://github.com/hlop3z/fastberry
copyright: Copyright © Hlop3z

nav:
  - Fastberry:
      - Introduction: index.md
      - Diagram: diagram.md
      - FOCT: foct.md
      - Settings: settings.md
      - Applications:
          - Introduction: applications/index.md
          - Application: applications/application.md
          - GraphQL: applications/graphql.md
          - Types: applications/types.md
          - Forms: applications/forms.md
          - Manager: applications/manager.md
          - Commands: applications/commands.md
          - Router: applications/routers.md
      - SQL Database:
          - Migrations: databases/index.md
      - Middleware, Extension and Permissions:
          - Workflow: middleware/workflow.md
          - Middleware: middleware/middleware.md
          - Extension: middleware/extension.md
          - Permission: middleware/permissions.md
          - Plugin: middleware/plugin.md
          - Events: middleware/events.md
      # - Application Programming Interface:
      # - Fastberry API: apis/fastberry.md
      # - GraphQL API: apis/graphql.md
  - Getting Started:
      - Before Starting: getting-started/index.md
      - Installation: getting-started/installation.md
      - First Project: getting-started/first-project.md
      - First App: getting-started/first-app.md
      - First Type: getting-started/first-type.md
      - First Form: getting-started/first-form.md
      - First Manager: getting-started/first-manager.md

# Configurations
watch:
  - custom_theme

theme:
  custom_dir: custom_theme/
  name: material
  locale: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.annotate
    # - navigation.expand
  icon:
    logo: material/bike-fast

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
